version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk:slim
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: collect static
          command: |
            apt-get -y install python3-venv
            python3 -m venv venv
            . ./venv/bin/activate
            pip install -r requirements.txt
            python manage.py collectstatic --noinput
      - run:
          name: deploy
          command: |
            echo $GCLOUD_KEY > /tmp/.gcloud-key
            gcloud auth activate-service-account --key-file=/tmp/.gcloud-key
            gcloud config set project slow-gun
            gcloud -q app deploy app.yaml
