name: deploy
on: [push]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.x'
      - uses: google-github-actions/setup-gcloud@master
        with:
          project_id: slow-gun
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: |
          pip install -r requirements.txt
          python manage.py collectstatic --noinput
          gcloud -q app deploy app.yaml
